# Online Retail Data Analysis

## 1. Business Context

This project analyzes transaction-level data from an online retail business.

The objective is to understand sales performance, customer purchasing behavior,
product performance, and geographic trends using Python, Pandas, NumPy, and
data visualization.

### Key Business Questions

- How much revenue does the business generate?
- How does revenue change over time?
- Which products generate the most revenue?
- Which customers contribute the most revenue?
- Which countries generate the most sales?
- How frequently do customers purchase?
- Are there cancelled or unusual transactions?
- What patterns can help the business improve sales and customer retention?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("../data/raw/Online Retail.xlsx")

In [3]:
df.shape

(541909, 8)

In [4]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [6]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

In [7]:
negative_qty = df[df['Quantity'] < 0]
negative_qty.shape

(10624, 8)

In [8]:
negative_qty.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [9]:
negative_qty["InvoiceNo"].head(20).tolist()

['C536379',
 'C536383',
 'C536391',
 'C536391',
 'C536391',
 'C536391',
 'C536391',
 'C536391',
 'C536391',
 'C536506',
 'C536543',
 'C536543',
 'C536548',
 'C536548',
 'C536548',
 'C536548',
 'C536548',
 'C536548',
 'C536548',
 'C536548']

In [10]:
negative_qty["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
True     9288
False    1336
Name: count, dtype: int64

In [11]:
negative_qty_non_c = negative_qty[
    ~negative_qty["InvoiceNo"].astype(str).str.startswith("C")
]

negative_qty_non_c.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom

In [12]:
negative_qty_non_c["Description"].value_counts().head(20)

Description
check                         120
damages                        45
damaged                        42
?                              41
sold as set on dotcom          20
Damaged                        14
thrown away                     9
Unsaleable, destroyed.          9
??                              7
damages?                        5
wet damaged                     5
ebay                            5
smashed                         4
missing                         3
CHECK                           3
wet pallet                      3
Dotcom sales                    2
reverse 21/5/10 adjustment      2
counted                         2
crushed                         2
Name: count, dtype: int64

In [13]:
zero_price = df[df['UnitPrice'] == 0]
zero_price.shape

(2515, 8)

In [14]:
zero_price.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [15]:
zero_price["Quantity"].value_counts().head(20)

Quantity
 1     402
 2     130
 3      84
-1      79
-2      58
-5      46
 4      42
 5      40
-3      39
-6      36
-4      35
-30     32
-9      32
-10     29
 6      29
-7      25
-21     24
 10     22
 8      21
-8      21
Name: count, dtype: int64

In [16]:
zero_price["Quantity"].gt(0).sum(),zero_price["Quantity"].lt(0).sum(),zero_price["Quantity"].eq(0).sum()

(np.int64(1179), np.int64(1336), np.int64(0))

In [17]:
zero_price_positive = zero_price[zero_price["Quantity"] > 0]
zero_price_positive.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany
12008,537361,21777,NaN,5,2010-12-06 12:34:00,0.0,NaN,United Kingdom
13263,537430,85215,NaN,120,2010-12-06 16:05:00,0.0,NaN,United Kingdom
13959,537436,84270,NaN,7,2010-12-06 17:00:00,0.0,NaN,United Kingdom
13960,537437,90167,NaN,10,2010-12-06 17:00:00,0.0,NaN,United Kingdom

In [18]:
zero_price_positive["Description"].value_counts().head(20)

Description
check                              39
found                              25
adjustment                         14
FRENCH BLUE METAL DOOR SIGN 1       9
amazon                              8
FRENCH BLUE METAL DOOR SIGN 8       8
Found                               8
FRENCH BLUE METAL DOOR SIGN 4       7
FRENCH BLUE METAL DOOR SIGN No      7
OWL DOORSTOP                        7
FRENCH BLUE METAL DOOR SIGN 3       7
RECIPE BOX PANTRY YELLOW DESIGN     7
Amazon                              7
FRENCH BLUE METAL DOOR SIGN 7       6
FRENCH BLUE METAL DOOR SIGN 5       6
FRENCH BLUE METAL DOOR SIGN 6       6
RED KITCHEN SCALES                  6
?                                   6
FRENCH BLUE METAL DOOR SIGN 9       6
MINT KITCHEN SCALES                 6
Name: count, dtype: int64

In [19]:
zero_price_positive["InvoiceNo"].astype(str).str[0].value_counts()

InvoiceNo
5    1179
Name: count, dtype: int64

In [20]:
zero_price_positive["InvoiceNo"].value_counts().head(30)

InvoiceNo
539856    64
537534    57
545176    49
553521    40
558340    35
553539    31
546933    30
564530    29
552230     6
540832     5
539750     4
545160     4
564651     4
538877     3
559296     3
580366     3
540372     2
546406     2
556939     2
560283     2
563015     2
568567     2
574920     2
575579     2
581406     2
536414     1
536545     1
536546     1
536547     1
536549     1
Name: count, dtype: int64

In [21]:
zero_price_positive[
    zero_price_positive["CustomerID"].notna()
][["InvoiceNo", "StockCode", "Description", "Quantity", "CustomerID", "Country"]].head(30)

,InvoiceNo,StockCode,Description,Quantity,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,14410.0,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,12457.0,Switzerland
187613,553000,47566,PARTY BUNTING,4,17667.0,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,12415.0,Australia
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,16818.0,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,12507.0,Spain
285657,561916,M,Manual,1,15581.0,United Kingdom
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,14911.0,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,14646.0,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,14646.0,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,14646.0,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,14646.0,Netherlands
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,16133.0,United Kingdom
361825,568384,M,Manual,1,12748.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,15804.0,United Kingdom
395529,571035,M,Manual,1,12446.0,RSA
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,18059.0,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,12415.0,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,14110.0,United Kingdom
436961,574252,M,Manual,1,12437.0,France
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,12431.0,Australia

In [22]:
zero_price_negative = zero_price[zero_price["Quantity"] < 0]

In [23]:
zero_price_negative["Description"].value_counts().head(30)

Description
check                           120
damages                          45
damaged                          42
?                                41
sold as set on dotcom            20
Damaged                          14
thrown away                       9
Unsaleable, destroyed.            9
??                                7
damages?                          5
wet damaged                       5
ebay                              5
smashed                           4
missing                           3
CHECK                             3
wet pallet                        3
Dotcom sales                      2
reverse 21/5/10 adjustment        2
counted                           2
crushed                           2
wet/rusty                         2
printing smudges/thrown away      2
sold as 1                         2
?missing                          2
incorrect stock entry.            2
stock check                       2
adjustment                        2
damages wax                       2
wet rusty                         2
rusty throw away                  2
Name: count, dtype: int64

In [24]:
zero_price_negative.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom

In [25]:
pd.crosstab(
    negative_qty["InvoiceNo"].astype(str).str.startswith("C"),
    negative_qty["UnitPrice"] == (0)
)

UnitPrice  False  True
InvoiceNo
False          0   1336
True        9288      0

In [26]:
zero_price_positive["CustomerID"].notna().value_counts()

CustomerID
False    1139
True       40
Name: count, dtype: int64

In [27]:
id_counts = df["CustomerID"].notna().value_counts()
id_counts

CustomerID
True     406829
False    135080
Name: count, dtype: int64

In [28]:
pd.crosstab(
    df["CustomerID"].isna(),
    df["Quantity"] < 0,
    normalize="columns"
) * 100

Quantity        False      True
CustomerID
False       74.898407  83.819654
True        25.101593  16.180346

In [29]:
df[df["Description"].isna()].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom

In [30]:
df[df["Description"].isna()]["Quantity"].value_counts().head(20)

Quantity
 1     126
-1      73
 2      66
-2      52
-5      40
-3      35
 3      33
-6      30
-4      29
 5      27
-9      26
 4      23
 6      22
-10     21
-7      21
-8      19
 8      18
-21     17
-30     16
 10     15
Name: count, dtype: int64

In [31]:
pd.crosstab(
    df["Description"].isna(),
    df["UnitPrice"] == 0
)

UnitPrice     False  True
Description
False        539394   1061
True              0   1454